### ISSUE TITLE
I'd like to contribute to your open-source project.

### ISSUE THREAD

**Issue by core116** [jinjat-data/jinjat#20]
Hi Emre 
I saw your job on upwork and this is a little exciting to me because this job is solid matching my skills
I am specialized in python and js/ts frontend framework
I'd like to discuss this particular opportunity with you soon 🙏

Here is my email address: devcore116@gmail.com
my whatsapp: +1 217 374 8105

**Comment by buremba** [comment]
Do you mind letting me know your Upwork name?

**Comment by core116** [comment]
Yes, I already applied for one of your job postings
I saw you posted two jobs with same name.
My name is Chris R.

**Comment by core116** [comment]
Are you interested in my proposal?

**Comment by buremba** [comment]
Let's continue the discussion on Upwork.

**Comment by core116** [comment]
Sounds good. I will be on there

**Comment by core116** [comment]
> Let's continue the discussion on Upwork.

👍 i didn't get message from you yet
